- client/static/assets/views/_partials/runs-active-table.html
- client/static/assets/views/_partials/runs-finished-table.html
The empty table is ugly :(  Added a sample message.
> Add messages when no runs available

- client/static/assets/stylus/app.styl
Check any individual loan detail, size your browser down.
> Ensure cookie crumbs wrap on small screens

- client/static/404.html
- client/static/assets/stylus/app.styl
- client/static/assets/views/_partials/runs-active-table.html
- client/static/assets/views/_partials/runs-finished-table.html
- client/static/assets/views/run-detail.html
- client/static/assets/views/runs.html
- client/static/index.html
-  I saw that there were properties of 'hasActive' and 'hasInactive', so I didn't need to check run length for conditions.  
-  Chrome was showing the Google favicon for some reason, so I added Mozilla.org favicons
-  Floats and widths and margins are awful.  I'm switching to flexbox, which is a bit more code, but it's the future™
> Move to flexbox columns, update conditionals logic, add shortcut icons

- client/static/assets/views/_partials/runs-active-table.html
- client/static/assets/views/_partials/runs-finished-table.html
-  Showing the "Runs" table header all the time, because the table looks odd without it.
-  Updating to `ng-show` for conditional show logic.
Apologies for the small update -- still getting acquainted with Angular
> Basic update to table head logic

- package.json
> Compile Stylus assets before starting server

- package.json
- server/index.js
Just some general maintenance...
Fixes #49 
Current output:
```sh
$ npm run outdated
> loads-web@1.0.0 outdated /Users/pdehaan/dev/github/loads-web
> npm outdated --depth 0
Package           Current  Wanted  Latest  Location
mockloadsresults    1.0.0     git     git  mockloadsresults
$ npm run shrinkwrap
> loads-web@1.0.0 shrinkwrap /Users/pdehaan/dev/github/loads-web
> npm shrinkwrap --dev
wrote npm-shrinkwrap.json
> loads-web@1.0.0 postshrinkwrap /Users/pdehaan/dev/github/loads-web
> nsp audit-shrinkwrap
No vulnerable modules found
```
I believe we have a separate tracking bug to remove the mock loads data since it was confusing. 
(**UPDATE:** see bug #43)
> Updating dependencies and adding npm tasks

- .awsbox.json
- README.rst
- package.json
- scripts/postdeploy.sh
- server/index.js
- server/routes/GET-broker.js
The results of last week's hack session with @karlht and @rpappalax.
> Add awsbox and broker API proxy

- client/static/assets/scripts/controllers.js
Basic update for JSON formatting.
> Formatting JSON output from generation form

- server/controllers/proxy.js
- server/routes/broker.js
Today's pair-programming session with @rpappalax.
> Add a proxy route for Grafana dashboards

- client/static/assets/scripts/controllers.js
- client/static/assets/stylus/app.styl
- client/static/assets/views/_partials/header-nav.html
- client/static/assets/views/projects.html
- package.json
- server/routes/gist.js
Initial commit for pulling gist info from GitHub.
> First step in pulling gist information from GitHub

- client/static/assets/scripts/controllers.js
- client/static/assets/stylus/app.styl
- package.json
- server/controllers/gist.js
- server/routes/gist.js
> Tweaking the gist server handler and some UI

- .travis.yml
- README.rst
pretty basic for now, but at least this will do auto-linting on checkin.
> Add travis.

- client/static/assets/scripts/controllers.js
- client/static/assets/views/projects.html
- server/controllers/schema.js
- server/routes/api.js
- server/schema.js
Async validation of a loaded Gist using Joi.
> Use Joi to validate a loaded gist

- .editorconfig
Adding this for the sake of me not doing horrific whitespacing.
> Add EditorConfig file to project

- .eslintrc
- client/static/assets/scripts/controllers.js
- client/static/assets/views/projects.html
Instead of dumping in HTML element messages and balancing all that, HTML5 notifications ftw.
> Add HTML5 notifications to the gist validation button

- .eslintignore
- .eslintrc
- .travis.yml
- Gruntfile.js
- README.md
- client/.eslintrc
- client/static/assets/stylus/app.styl
- client/static/assets/stylus/fonts.styl
- client/static/assets/views/_partials/footer-nav.html
- config/local.json
- grunttasks/default.js
- grunttasks/eslint.js
- grunttasks/stylus.js
- package.json
- server/config.js
- server/routes/404.js
- server/routes/api.js
- server/routes/comments.js
- server/routes/gist.js
- server/routes/home.js
- server/routes/static.js
> Adding Grunt tasks for ESLint and Stylus

- client/static/assets/scripts/persona.js
- client/static/assets/views/_partials/header-nav.html
- client/static/index.html
- package.json
- server/controllers/login.js
- server/controllers/schema.js
- server/routes/auth.js
- server/routes/static.js
- server/views/login.html
> Removing johnny/quest and adding Persona

- client/.eslintrc
- client/static/assets/scripts/persona.js
- package.json
- server/controllers/login.js
> Only let @mozilla emails log in

- server/controllers/proxy.js
> Forward query params to the broker

- .eslintrc
- .travis.yml
- client/static/assets/scripts/controllers.js
- client/static/assets/scripts/persona.js
- client/static/assets/scripts/services.js
- package.json
- server/controllers/login.js
- server/controllers/project.js
- server/controllers/proxy.js
- server/controllers/schema.js
- server/db.js
- server/index.js
> Fixing some ESLint warnings and errors
